Mounth 9/project 1
IvannaBalanyuk/react-stellar-burger pull request #7
Opened 2023-10-23 15:12 UTC by IvannaBalanyuk

2023-10-23 16:19 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Хорошая работа с формами - использовали хук `useForm`
- Правильно настроили роутинг модальных окон
- Есть автологин

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- После успешного прохождения запроса на регистрацию необходимо переводить юзера на главную страницу под авторизованных акаунтом.
- Процедура восстановления пароля не работает. У вас немного неправильная структура в body запроса. У вас получился эмейл в объект, который тоже в объекте.

![image](https://github.com/IvannaBalanyuk/react-stellar-burger/assets/60173362/21fb06b7-b519-4ff2-8eb6-ab6fc2a9c7ce)

- Поле с password не попадает в body запроса на изменение данных профиля
 
![image](https://github.com/IvannaBalanyuk/react-stellar-burger/assets/60173362/942e9371-7dbf-4740-be71-4d727720a1b6)

- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью ` return <Navigate to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Navigate`)

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-23 16:19 UTC, andryxxa93 commented on src/components/app/app/app.jsx
> +          <Route path="/ingredients/:ingredientId" element={<Ingredient />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-10-23 18:57 UTC, IvannaBalanyuk commented
Здравствуйте! Спасибо за оперативное и продуктивное ревью)
Внесла правки. Есть сомнения насчет первого пункта, не уверена, что правильно реализовала

2023-10-24 06:08 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-10-28 15:43 UTC, merged